# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: DNSControl Action
description: DNSControl GitHub Action using configurable GitHub release
author: Eli Heady <eli.heady@gmail.com>

inputs:

  check:
    default: 'false'
    description: Run `dnscontrol check` before any other commands - default is 'false'
    required: false

  version:
    default: 'latest'
    description: Desired version to run (default 'latest')
    required: false

  cmdargs:
    description: DNSControl command and optional arguments
    required: true

  dnsconfig_file:
    default: dnsconfig.js
    description: Path to dnsconfig.js. Defaults to 'dnsconfig.js' (at repository root)
    required: false

  creds_file:
    default: creds.json
    description: Path to creds.json. Defaults to 'creds.json' (at repository root)
    required: false

  output_file:
    default: ''
    description: Write DNSControl output to this file
    required: false

  post_pr_comment:
    default: 'false'
    description: Post the DNSControl output in a PR comment (default 'false')
    required: false

  post_summary:
    default: 'false'
    description: Post the DNSControl output in the step summary (default 'false')
    required: false

outputs:
  output:
    description: DNSControl output
    value: ${{ steps.dnscontrol.outputs.output }}
  output_file:
    description: DNSControl output written to file
    value: ${{ steps.write_file.outputs.output_file }}


runs:
  using: composite
  steps:

    - name: Sanitize inputs
      env:
        DNSCONTROL_VERSION: ${{ inputs.version }}"
        OUTPUT_FILE: ${{ inputs.output_file }}"
        DNSCONFIG_FILE: ${{ inputs.dnsconfig_file }}"
        CREDS_FILE: ${{ inputs.creds_file }}"
      shell: bash
      run: |
        if [ ! -e $DNSCONFIG_FILE ]; then
          echo "the specified dnsconfig_file does not exist in workspace"
          exit 1
        fi
        if [ ! -e $CREDS_FILE ]; then
          echo "the specified creds_file does not exist in workspace"
          exit 1
        fi
        if [[ ! $DNSCONTROL_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "invalid DNSControl version format"
          exit 1
        fi
        cat >>"$GITHUB_ENV"<<EOF
        DNSCONTROL_VERSION="$DNSCONTROL_VERSION"
        OUTPUT_FILE="$OUTPUT_FILE"
        DNSCONFIG_FILE="$DNSCONFIG_FILE"
        CREDS_FILE="$CREDS_FILE"
        EOF

    - name: Resolve download URL for latest
      if: ${{ inputs.version == 'latest' }}
      shell: bash
      run: |
        echo "Resolve download URL for latest"
        CURL='curl -H user-agent:stackexchange-dnscontrol-action -fsS --retry 5 --retry-max-time 30'
        echo "CURL=$CURL" >>"$GITHUB_ENV"
        URL=$(\
          $CURL -L https://api.github.com/repos/StackExchange/dnscontrol/releases/latest \
          | jq -r '.assets[] | select(.name? | match("dnscontrol_*.*.*_linux_amd64.tar.gz$")) | .browser_download_url'\
        )
        echo "URL=$URL" >>"$GITHUB_ENV"

    - name: Resolve download URL
      if: ${{ inputs.version != 'latest' }}
      shell: bash
      run: |
        echo "Resolve download URL for $DNSCONTROL_VERSION"
        URL=$(\
          $CURL -L https://api.github.com/repos/StackExchange/dnscontrol/releases \
          | jq -r '.[] | select(.tag_name == "$DNSCONTROL_VERSION") | .assets[] | select(.name? | match("dnscontrol_*.*.*_linux_amd64.tar.gz$")) | .browser_download_url' \
        )
        echo "URL=$URL" >>"$GITHUB_ENV"

    - name: Download DNSControl
      shell: bash
      run: |
        echo "Download DNSControl $DNSCONTROL_VERSION"
        $CURL -L "${URL}" \
          | tar -xvzf - dnscontrol
        DNSCONTROL=$(readlink -f dnscontrol)
        echo "DNSCONTROL=$DNSCONTROL" >>"$GITHUB_ENV"
        $DNSCONTROL version

    - name: DNSControl check
      if: ${{ inputs.check == 'true' }}
      continue-on-error: true
      id: check
      shell: bash
      env:
        NO_COLOR: 'true'
      run: |
          echo "DNSControl check"
          set +e
          DNSCONTROL_CMD=$($DNSCONTROL check --config "$DNSCONFIG_FILE")
          err=$?
          export DNSCONTROL_CMD
          DELIMITER="DNSCONTROL-$RANDOM"
          {
            echo "output<<$DELIMITER"
            echo "$DNSCONTROL_CMD"
            echo "$DELIMITER"
          } >>"$GITHUB_OUTPUT"
          echo $DNSCONTROL_CMD
          exit $err

    - name: Check Summary
      # write check output to job summary if check failed
      if: ${{ steps.check.outcome != 'skipped' && steps.check.outcome != 'success' }}
      shell: bash
      run: |
        echo "Check Summary"
        cat >${GITHUB_STEP_SUMMARY}<<EOF
        outcome was ${{ steps.check.outcome }}
        ${{ steps.check.outputs.output }}
        EOF
        exit 1

    - name: DNSControl
      id: dnscontrol
      # execute only if check was ok or skipped
      if: ${{ (steps.check.outcome != 'skipped' && steps.check.outcome == 'success' ) || steps.check.outcome == 'skipped' }}
      continue-on-error: true
      shell: bash
      env:
        NO_COLOR: 'true'
        DNSCONTROL_COMMAND: ${{ inputs.cmdargs }}
      run: |
          echo "DNSControl"
          set +e
          DNSCONTROL_CMD=$($DNSCONTROL "$DNSCONTROL_COMMAND" --config "$DNSCONFIG_FILE" --creds "$CREDS_FILE")
          err=$?
          DELIMITER="DNSCONTROL-$RANDOM"
          {
            echo "output<<$DELIMITER"
            echo "$DNSCONTROL_CMD"
            echo "$DELIMITER"
          } >>"$GITHUB_OUTPUT"
          exit $err

    - name: Write output file
      id: write_file
      # execute if user specified an output file AND dnscontrol job ran
      if: ${{ inputs.output_file != '' && steps.dnscontrol.outcome != 'skipped' }}
      shell: bash
      env:
        OUTPUT_FILE: ${{ inputs.output_file }}
      run: |
        echo "Write output file"
        echo "${{ steps.dnscontrol.outputs.output }}" > $OUTPUT_FILE
        echo "output_file=$OUTPUT_FILE" >>"$GITHUB_OUTPUT"

    - name: Attach Results as PR comment
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      # execute if user set post_pr_comment, this is a PR event, AND dnscontrol job ran
      if: ${{ inputs.post_pr_comment && github.event.pull_request.number != '' && steps.dnscontrol.outcome != 'skipped' }}
      with:
        comment-tag: dnscontrol_preview_push_external
        message: |
          <details open><summary>Results</summary>

          ### DNSControl Results

          ```
          ${{ steps.dnscontrol.outputs.output }}
          ```
          </details>

    - name: Job Summary
      id: job_summary
      # execute if user set post_summary AND dnscontrol job ran
      if: ${{ inputs.post_summary == 'true' && steps.dnscontrol.outcome != 'skipped' }}
      shell: bash
      run: |
        echo "Job Summary"
        cat >${GITHUB_STEP_SUMMARY}<<EOF
        ${{ steps.dnscontrol.outputs.output }}
        EOF
