name: 'Run Linters'

on:
  pull_request:
    paths:
      - '*/action.yml'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install yq
        uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
      
      - name: Install shellcheck
        run: |
          CURL='curl -fsS --retry 5 --retry-max-time 30'
          URL=$(\
            $CURL -L https://api.github.com/repos/koalaman/shellcheck/releases/latest \
            | jq -r '.assets[] | select(.name? | match("shellcheck_*.*.*.linux.x86_64.tar.xz$")) | .browser_download_url'\
          )
          VERSION=$(\
            $CURL -L https://api.github.com/repos/koalaman/shellcheck/releases/latest \
            | jq -r '.tag_name'\
          )
          $CURL -L "${URL}" | tar -xvzf - shellcheck-$VERSION/shellcheck
          echo "$(PWD)/shellcheck-$VERSION/shellcheck" >> "$GITHUB_PATH"
          SHELLCHECK=$(readlink -f shellcheck)
          echo "SHELLCHECK=$SHELLCHECK" >>"$GITHUB_ENV"
          $SHELLCHECK version

      - name: Run shellcheck
        run: bin/shellcheck.sh

