# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: DNSControl

permissions: 
  contents: read

on:
  workflow_call:
    inputs:
      cmdargs:
        type: string
        description: DNSControl command and optional arguments
        required: true

      dnsconfig_file:
        type: string
        default: dnsconfig.js
        description: Path to dnsconfig.js. Defaults to 'dnsconfig.js' (at repository root)
        required: false

      creds_file:
        type: string
        default: creds.json
        description: Path to creds.json. Defaults to 'creds.json' (at repository root)
        required: false

      output_file:
        type: string
        default: ''
        description: Write DNSControl output to this file
        required: false
      
      post_pr_comment:
        type: boolean
        default: false
        description: Post the DNSControl output in a PR comment
        required: false

      post_summary:
        type: boolean
        default: false
        description: Post the DNSControl output in the step summary
        required: false


jobs:
  preview:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: DNSControl check
        uses: eliheady/dnscontrol-action-experimental@v4.23.0-patch0
        env:
          NO_COLOR: 'true'
        with:
          cmdargs: "check"

      - name: DNSControl
        id: dnscontrol
        uses: eliheady/dnscontrol-action-experimental@v4.23.0-patch0
        with:
          cmdargs: ${{ inputs.cmdargs }}
        env:
          NO_COLOR: 'true'

      - name: Attach Results as PR comment
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ inputs.post_pr_comment }}
        with:
          comment_tag: dnscontrol_preview_push_external
          message: |
            <details open><summary>Results</summary>

            ### DNS Control Results

            ```
            ${{ steps.dnscontrol.outputs.output }}
            ```
            </details>

      - name: Summary
        if: ${{ inputs.post_summary }}
        env:
         DNSCONTROL_OUTPUT: ${{ steps.dnscontrol.outputs.output }}
        run: |
          echo "$DNSCONTROL_OUTPUT" > "$GITHUB_STEP_SUMMARY"